version: "3.9"
services:
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE_HOST: db
      MYSQL_DATABASE: mysql-db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE_PORT: 3306
    volumes:
      - ./backend/admin/.dbdata:/var/lib/mysql
    ports:
      - 33066:3306
  backend:
    container_name: backend-django
    build:
      context: ./backend/admin
      dockerfile: Dockerfile
    command: bash -c "python check_db.py --service-name db --ip db --port 3306 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./backend/admin:/app
    depends_on:
      - db
    environment:
      MYSQL_DATABASE_HOST: db
      MYSQL_DATABASE: mysql-db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE_PORT: 3306
  frontend:
    container_name: frontend-nginx
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_ENV: 'carloserl-dev-compose'
        REACT_APP_BE: ''
    ports:
      - "8080:80"
    depends_on:
      - backend
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
