apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-app
  template:
    metadata:
      labels:
        app: server-app
    spec:
      containers:
        - name: server-app
          image: carloserl/fullstack-kubernetes_backend:1.01
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "python manage.py migrate && python manage.py runserver 0.0.0.0:8000",
            ]
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_DATABASE
              value: mysql-db
            - name: MYSQL_DATABASE_HOST
              value: mysql-cluster-ip-service
            - name: MYSQL_DATABASE_PORT
              value: "3306"
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: root

            # - name: MYSQL_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: pgpassword
            #       key: PGPASSWORD
