frontend:
  name: client-app
  replicaCount: 1

backend:
  name: server-app
  replicaCount: 1
  env:
    - name: MYSQL_DATABASE
      value: mysql-db
    - name: MYSQL_DATABASE_HOST
      value: mysql-cluster-ip-service
    - name: MYSQL_DATABASE_PORT
      value: 3306
    - name: MYSQL_USER
      value: root
    - name: MYSQL_PASSWORD
      value: root
    - name: MYSQL_ROOT_PASSWORD
      value: root

database:
  name: mysql-app
  replicaCount: 1
  env:
    - name: MYSQL_DATABASE
      value: mysql-db
    - name: MYSQL_DATABASE_HOST
      value: mysql-cluster-ip-service
    - name: MYSQL_DATABASE_PORT
      value: 3306
    - name: MYSQL_USER
      value: root
    - name: MYSQL_PASSWORD
      value: root
    - name: MYSQL_ROOT_PASSWORD
      value: root
