version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command : bash -c "python check_db.py --service-name db --ip db --port 3306 && 
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      MYSQL_DATABASE_HOST: db
      MYSQL_DATABASE: mysql-db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE_PORT: 3306
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE_HOST: db
      MYSQL_DATABASE: mysql-db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE_PORT: 3306
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
